export const AuditActions = {
  USER_SYNCED: "USER_SYNCED",
  PRODUCT_CREATED: "PRODUCT_CREATED",
  PRODUCT_UPDATED: "PRODUCT_UPDATED",
  PRODUCT_DEACTIVATED: "PRODUCT_DEACTIVATED",
  PRODUCT_REACTIVATED: "PRODUCT_REACTIVATED",
  CATEGORY_CREATED: "CATEGORY_CREATED",
  CATEGORY_UPDATED: "CATEGORY_UPDATED",
  CATEGORY_DEACTIVATED: "CATEGORY_DEACTIVATED",
  STOCK_ADJUSTED: "STOCK_ADJUSTED",
  STOCK_DEDUCTED: "STOCK_DEDUCTED",
  STOCK_REVERTED: "STOCK_REVERTED",
  ORDER_CREATED: "ORDER_CREATED",
  ORDER_STATUS_UPDATED: "ORDER_STATUS_UPDATED",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  ORDER_AUTO_CANCELLED: "ORDER_AUTO_CANCELLED",
  STORE_CONFIG_UPDATED: "STORE_CONFIG_UPDATED",
} as const;

export type AuditAction = (typeof AuditActions)[keyof typeof AuditActions];
